1、DeepWalk代码通过Word2Vec将社交网络中的节点（研究人员、艺术家、运动员）转换为低维向量表示，这是典型的图嵌入应用。Word2Vec原本用于自然语言处理，但通过随机游走策略可将图结构转化为类似文本的序列数据，从而适配Word2Vec的训练逻辑。
2、create_social_network构建了一个包含45个节点的异构图，节点间通过概率规则建立连接，generate_random_walks函数模拟在图中随机游走，生成类似文本的节点序列，作为Word2Vec的输入；learn_embeddings调用Word2Vec的Skip-gram模型，将游走序列映射为64维向量，捕捉节点间的相似性。
3、通过calculate_similarity_matrix计算节点向量的余弦相似度，最终可用于可视化，展示不同职业群体间的关联强度。这种流程直接继承了Word2Vec在语义相似度计算上的优势，但将其扩展到了图数据领域。
